### ISSUE TITLE
Reactive Extensions - No full stacktrace in Event Viewer when an exception is thrown

### ISSUE THREAD

**Issue by Pellared** [Reactive-Extensions/Rx.NET#120] opened 2015-07-27 12:00 UTC
Several times using Reactive Extensions caused the application to crash!
Please see more information here (I do not want to duplicate): http://stackoverflow.com/questions/31563866/reactive-extensions-asynclock-wait-throws-argumentnullexception

**Comment by Pellared** [comment] 2015-07-30 06:49
It occurs that the code that is throwing the Exception is "my" code. However the Event Viewer does not show the full stacktrace. Do you know why?

**Comment by shiftkey** [comment] 2016-07-12 22:00
> However the Event Viewer does not show the full stacktrace. Do you know why?

If you look at [the source](https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/System.Reactive.Core/Reactive/Concurrency/DefaultScheduler.cs#L118) this error isn't being raised due to your code, but due to passing `null` into the `Select` as discussed in the SO thread. So I believe that stack trace is accurate.

**Comment by shiftkey** [comment] 2016-07-12 22:01
Closing this out as "working as designed" - let me know if you have any other feedback on this.

**Closed by shiftkey** 2016-07-12 22:01 UTC
