### ISSUE TITLE
C++/CLI Compatibility?

### ISSUE THREAD

**Issue by BenjaminHolland** [Reactive-Extensions/Rx.NET#233] opened 2016-07-19 23:00 UTC
It'd be nice to be able to use these extensions from C++.

**Comment by onovotny** [comment] 2016-07-20 00:38
Hi @BenjaminHolland,

What is the issue with using them from C++/CLI today? Also, have you considered https://github.com/Reactive-Extensions/RxCpp?

**Comment by BenjaminHolland** [comment] 2016-07-20 00:45
The Reactive.Interactive package doesn't install. I did try using RxCpp,
but it works on stl containers, not managed enumerables.

On Jul 19, 2016 5:38 PM, "Oren Novotny" <notifications@github.com> wrote:
>
> Hi @BenjaminHolland,
>
> What is the issue with using them from C++/CLI today? Also, have you
considered https://github.com/Reactive-Extensions/RxCpp?

**Comment by onovotny** [comment] 2016-07-20 00:50
What does the output of the install look like, do you have a simple repro we can look at? I don't think anyone has tried this scenario.

Thanks!

**Comment by BenjaminHolland** [comment] 2016-07-20 00:53
Don't have a repo, but all I have to do to reproduce is create a new
c++/cli console project and use the nuget package manager. "Install-package
System.Interactive" results in an error. By the by, you need to update the
nuget package listing for the IX extensions in the readme as well.

**Comment by onovotny** [comment] 2016-07-20 01:23
I can confirm but this appears to be a NuGet bug.

`Could not install package 'System.Interactive 3.0.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

/cc @yishaigalatzer

**Comment by BenjaminHolland** [comment] 2016-07-20 01:26
It looks like it's an issue with the nuget package to me.

**Comment by onovotny** [comment] 2016-07-20 01:30
@BenjaminHolland I believe the issue is with NuGet's logic itself and have looped in the NuGet team. I believe you'll find the same issue with lots of other packages, like Newtonsoft.Json 9.0.1.

**Comment by BenjaminHolland** [comment] 2016-07-20 01:34
Ok. Do you have a link to the issue I can track?

**Comment by onovotny** [comment] 2016-07-20 01:37
I filed it here: https://github.com/NuGet/Home/issues/3171

**Comment by BenjaminHolland** [comment] 2016-07-20 01:39
Thank you. Hope they fix it quick.

**Comment by shiftkey** [comment] 2016-07-20 18:27
Closing this out as an upstream issue

**Closed by shiftkey** 2016-07-20 18:27 UTC
Labels: bug, external
