### ISSUE TITLE
Subscribe / Disposable design

### ISSUE THREAD

**Issue by Igorbek** [Reactive-Extensions/Rx.NET#71] opened 2014-12-10 01:15 UTC
_(It's just a thoughts that I have for a while and didn't find an answer yet)_

I found that there's a lack in the core Rx design (in Rx contract). Maybe it's just my misunderstanding, but I still haven't found an answer.

There's a use case when observer can start to get notification before it gets subscription disposable. And if observable don't use any scheduler and keep firing notifications once it captured execution flow, there's no chance to consumer to stop it.

I suppose it's only related to `Scheduler.Immediate`.
Consider such observable:

```cs
Observable.Range(0, 1000, Scheduler.Immediate)
```

For any subscriber there's no way to unsubscribe until subscription will complete iterating.
It's weird, because the consumer's code will be executed through observer. And it would be nice to have ability to unsubscribe from within observer.

As I see the implementation you introduced specific `IteratorScheduler` and `AutoDetachObserver` to provide a way to stop such subscriptions. But they're so complicated.

Why you didn't provide a way to pass subscription (cancellation disposable) through regular execution flow? Like,

1. extra parameter with type `IDisposable` in `On*` methods, or
2. additional method like `void OnSubscribe(IDisposable subscription)` of `IObserver` which should be called once per subscription before send any notification (in this case we couldn't share observer between subscription and have ability to unsubscribe from specific subscription).

So, as I said, it's just my thoughts and want to clarify why such decision was made.

**Comment by bartdesmet** [comment] 2015-04-15 05:50
Interesting discussion. All of the points mentioned above are by design conform the current Rx algebra; there's no action items for us right now, so I'm closing this "issue". Feel free to reopen if you have more questions.

**Closed by bartdesmet** 2015-04-15 05:50 UTC
